aws/aws-nitro-enclaves-cli

README.md
Include the link reference to the AWS docs user guide for the Nitro
Enclaves CLI.
=> README: Include reference to AWS user guide for the Nitro CLI

src/common/commands_parser.rs, src/common/document_errors.rs, src/common/logger.rs, src/enclave_proc/commands.rs, src/enclave_proc/cpu_info.rs, src/enclave_proc/resource_manager.rs, src/enclave_proc/socket.rs, src/enclave_proc/utils.rs, src/enclave_proc_comm.rs, src/lib.rs, tests/test_dev_driver.rs
Improves the error messsages displayed when a file
operation fails, by outputting the file name as well
as the attempted operation.
=> cli: Improve file operation error messages

src/common/document_errors.rs
Updated the error messages related to insufficient memory / CPUs
available, specifying the steps to perform in order to increase
memory / CPU pool size.
=> cli: improve insufficient resources error messages

bootstrap/nitro-enclaves-allocator
When specifying a CPU pool in allocator.yaml, the service
was calling an undefined function. This commit defines
the get_enclave_cpus function.
Signed-off-by: Alexandra Pirvulescu <alexprv@amazon.com>
Issue #192 
=> nitro-enclaves-allocator: Add get_enclave_cpus function

bootstrap/nitro-enclaves-allocator
Previously, restarting the allocator service would produce
some errors with regard to the CPUs, when trying to
reserve more than `parent_instance_cpus / 2` CPUs.
This commit fixes the issue, by first bringing back
online the CPUs and then looking for CPUs to include
in the CPU pool.
=> allocator-service: added possibility to restart service

src/common/document_errors.rs, src/enclave_proc/resource_manager.rs, src/utils.rs, tests/tests.rs
Currently, before starting an enclave, the user provided
enclave memory is checked to be at least equal to the EIF
size.
However, this constraint is not strong enough and in order
to ensure there is enough memory to unpack the initramfs,
this commit introduces a lower limit on the enclave memory:
4 times the size of the EIF file.
*Issue #, if available: #188, #194, #196*
=> cli: Ensure enclave is started with enough memory

src/common/mod.rs, src/enclave_proc/connection.rs, src/enclave_proc/mod.rs, src/enclave_proc/resource_manager.rs, src/enclave_proc_comm.rs, src/main.rs, tests/tests.rs
The enclave needs to be started in debug mode to get its console output.
Check the enclave flags and early exit if the debug mode flag is not
set when the enclave is created.
*Issue #193*
=> nitro-cli: Check debug flag is present for enclave console access

README.md
The Nitro Enclaves kernel driver is available in the Ubuntu v5.4 Linux
kernel. Add this info to the list of distros that have integrated the NE
kernel driver.
=> README: Update Nitro Enclaves kernel driver availability info

Cargo.lock
cargo-audit would report errors with respect to
the crate versions used for smallvec. Updated the
versions from 0.6.13 to 0.6.14 (checksum taken
from https://github.com/rust-lang/crates.io-index/blob/master/sm/al/smallvec/#L48)
and from 1.2.0 to 1.6.1 (checksum taken from
https://github.com/rust-lang/crates.io-index/blob/master/sm/al/smallvec/#L49).
=> smallvec: update crate version

Cargo.lock
This PR fixes a bug in `yaml-rust` that causes the following error
```
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<yaml::Yaml, yaml::Yaml>` uninitialized, which is invalid', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/mem/mod.rs:659:9
stack backtrace:
<snip>
at ./rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/mem/mod.rs:659:9
4: linked_hash_map::LinkedHashMap<K,V,S>::ensure_guard_node
at ./home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:174:52
5: linked_hash_map::LinkedHashMap<K,V,S>::insert
at ./home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:304:9
6: <serde_yaml::ser::SerializeStruct as serde::ser::SerializeStruct>::serialize_field …
```
=> Bump yaml-rust version

Cargo.lock, Cargo.toml, SPECS/aws-nitro-enclaves-cli.spec
Currently, plain RPM package upgrades leave the nitro-cli
into an unusable state, since the post-uninstall scriptlet
removes necessary files and directories.
Checking the package operation in both pre and post
uninstall is necessary in order to successfully run
nitro-cli commands after performing an install operation
(e.g. `sudo yum update aws-nitro-enclaves-cil`).
The meaning of the parameter values are described here:
https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/.
Instead of relying on the user to manually update his
already installed v1.0-5 of the Nitro CLI package, this
commit introduces a separate `%posttrans` scriptlet
that currently performs the same `%post` steps as before,
in order to reconfigure the environment after the old
package version uninstall. …
=> packaging: Prevent file erasure on package upgrade

sources
Ran `make update-crates-dependencies` to update
the vendorized dependencies in the S3 bucket.
=> deps: Update vendorized dependencies

Cargo.lock, eif_defs/src/lib.rs, eif_utils/src/bin/eif_build.rs, eif_utils/src/lib.rs, enclave_build/Cargo.toml, enclave_build/src/docker.rs, enclave_build/src/lib.rs
When building an EIF image, inspect the source docker
image and based on its architecture (i.e. amd64 vs aarch64)
set the flag accordingly in the EIF header flags.
This flag shall be cleared for amd64 and toggled for aarch64.
Signed-off-by: Alexandru Ciobotaru <alcioa@amazon.com>
=> eif: Add EIF header architecture flag

build.rs, enclave_build/src/docker.rs, run_tests.sh, src/common/document_errors.rs, src/enclave_proc/connection.rs, src/enclave_proc/resource_manager.rs, tools/Dockerfile1804, vsock_proxy/src/main.rs, vsock_proxy/src/starter.rs
This commit solves several errors reported
by rustfmt and clippy as a result of updating to
rust 1.49
=> clippy: Fix rustfmt & clippy errors

README.md, src/common/document_errors.rs
https://github.com/aws/aws-nitro-enclaves-cli/issues/232
This adds some clarity around the requirement for Linux hugepages, etc.
=> Add docs about hugepages

drivers/virt/nitro_enclaves/Dockerfile
Update the version of the kernel headers to the latest version since the
current version is not available anymore in the repo.
=> nitro_enclaves: Update the version of kernel headers in the Dockerfile

Cargo.lock, Cargo.toml
Remove memmap and update inotify to remove the cargo-audit warnings generated by some dependencies.
=> Fix cargo-audit warnings

enclave_build/src/docker.rs, run_tests.sh, tests/tests.rs
Check if the Docker image used for building the enclave image is locally
available, before trying to pull a remote Docker image. Early exit if
the Docker image is locally available.
Update the tests to use the locally built Docker image of the command
executer, instead of the remote one, to cover this test case.
*Issue #239*
=> nitro-cli: Fix Docker pull image logic

Makefile
When the Rust crates dependencies are updated, the information about
licenses in THIRD_PARTY_LICENSES_RUST_CRATES.html has to be updated.
Add a Makefile target to generate the updated version of the
THIRD_PARTY_LICENSES_RUST_CRATES.html file, to be used when there are
changes in the Rust crates dependencies.
=> Makefile: Add target for updating THIRD_PARTY_LICENSES_RUST_CRATES.html

vsock_proxy/service/nitro-enclaves-vsock-proxy.service
The start command for the nitro-enclaves-vsock-proxy service uses IMDS
to retrieve the region corresponding to the running instance.
Update the start command to use IMDSv2.
Documentation for IMDSv2: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
=> vsock_proxy: Update nitro-enclaves-vsock-proxy service to use IMDSv2

vsock_proxy/service/nitro-enclaves-vsock-proxy.service
The configuration for the vsock-proxy service has been updated to use
IMDSv2. Add fallback to IMDSv1 if IMDSv2 is not available.
=> vsock_proxy: Add fallback to IMDSv1 if IMDSv2 not available

drivers/virt/nitro_enclaves/ne_misc_dev.c
A failing usercopy of the slot uid will lead to a stale entry in the
file descriptor table as put_unused_fd() won't release it. This enables
userland to refer to a dangling 'file' object through that still valid
file descriptor, leading to all kinds of use-after-free exploitation
scenarios.
Exchanging put_unused_fd() for close_fd(), ksys_close() or alike won't
solve the underlying issue, as the file descriptor might have been
replaced in the meantime, e.g. via userland calling close() on it
(leading to a NULL pointer dereference in the error handling code as
'fget(enclave_fd)' will return a NULL pointer) or by dup2()'ing a
completely different file object to that very file descriptor, leading
to the same situation: a dangling file descriptor pointing to a freed
object -- just in this case …
=> nitro_enclaves: Fix stale file descriptors on failed usercopy

tests/integration/helpers.py
The nitro-cli process could disappear from under us from various
reasons, for example the enclave could be in the process of terminating.
The solution is to catch exceptions when trying to kill the process and
consider them harmless.
Signed-off-by: Alexandru Gheorghe <aggh@amazon.com>
=> integration_tests: Fix race when cleanup nitro-cli process

README.md
The install from source instructions missed the step where we config the
local environment with the resources needed to run an enclaves.
This is normally handled by nitro-enclaves-allocator.service when we are
installing nitro-cli from the RPM package.
Signed-off-by: Alexandru Gheorghe <aggh@amazon.com>
=> Readme.md: Update instructions to install from source

drivers/virt/nitro_enclaves/Dockerfile
The following error can appear when using the current container setup:
Step 1 : FROM ubuntu:20.04
toomanyrequests: You have reached your pull rate limit. You may
increase the limit by authenticating and upgrading:
https://www.docker.com/increase-rate-limit
Update the source of the container base image to be AWS ECR.
https://gallery.ecr.aws/lts/ubuntu
=> nitro_enclaves: Update container base image source in Dockerfile

drivers/virt/nitro_enclaves/ne_pci_dev.c
Enable Bus Master for the NE PCI device, according to the PCI spec
for submitting memory or I/O requests:
Master Enable – Controls the ability of a PCI Express
Endpoint to issue Memory and I/O Read/Write Requests, and
the ability of a Root or Switch Port to forward Memory and
I/O Read/Write Requests in the Upstream direction
Cc: Andra Paraschiv <andraprs@amazon.com>
Cc: Alexandru Vasile <lexnv@amazon.com>
Cc: Alexandru Ciobotaru <alcioa@amazon.com>
Reviewed-by: Andra Paraschiv <andraprs@amazon.com>
Signed-off-by: Longpeng(Mike) <longpeng2@huawei.com>
Link: https://lore.kernel.org/r/20210621004046.1419-1-longpeng2@huawei.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
By submitting this pull request, I confirm that you …
=> nitro_enclaves: Set Bus Master for the NE PCI device

Cargo.lock, THIRD_PARTY_LICENSES_RUST_CRATES.html, eif_defs/Cargo.toml, eif_loader/Cargo.toml, eif_utils/Cargo.toml, enclave_build/Cargo.toml, enclave_build/src/docker.rs, run_tests.sh, tools/Dockerfile1804.aarch64, tools/Dockerfile1804.x86_64
After updating the enclave build codebase to match a newer version of
the shiplift crate, the async functionality is missing a couple of
checks of the docker image config.
Add the checks to not try later to unwrap a "None" variable.
=> enclave_build: Fix docker image checks during enclave image inspect

SPECS/aws-nitro-enclaves-cli.spec
July is not a valid month name so the rpmspec tool will complain when
trying to build it.
=> Fixup date in changelog

vsock_proxy/src/main.rs, vsock_proxy/src/starter.rs, vsock_proxy/tests/connection_test.rs
Allowlist matching is done by comparing the remote server's IP and port
against the IP and port of all allowlist file entries. The IP-based comparison
is prone to occasional false-negative failures - consider a case where a
hostname may resolve to different IP addresses at different times, due to
load-balancing, for example. The following may occur:
1) The IP of a host is obtained at moment T1, with value IP_1
2) Load balancing occurs and the host is switched with another one that has
a different IP, IP_2
3) The IP of the host as read from the allowlist is obtained at moment T2 > T1
and because of 2), it resolves to IP_2
4) IP_1 is compared against IP_2 and the check fails, thus preventing the
vsock-proxy from launching, even though the hostnames are the same.
This change fixes the …
=> vsock-proxy: Fix remote server's matching against allowlist

tools/Dockerfile1804.aarch64, tools/Dockerfile1804.x86_64
The following error appears when trying to build cargo audit using the
current Rust version present in the Dockerfiles (ENV RUST_VERSION=1.49.0).
Downloaded matches v0.1.8
Downloaded rustc-demangle v0.1.20
Downloaded zeroize v1.4.1
error: failed to compile `cargo-audit v0.15.0`, intermediate artifacts can be found at `/tmp/cargo-install0judLM`
Caused by:
failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zeroize-1.4.1/Cargo.toml`
Caused by:
feature `resolver` is required
this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["resolver"]` to enable this feature
The latest version of zeroize can be used with Rust version 1.51+.
cargo-audit has included in its Cargo.lock a dependency for zeroize 1.3.0. …
=> tools: Fix cargo audit build

Cargo.lock, Makefile, THIRD_PARTY_LICENSES_RUST_CRATES.html
nitro-cli: Update version of hyper crate
Fix the following error by updating to the latest version of the hyper
crate:
Crate:         hyper
Version:       0.14.4
Title:         Lenient `hyper` header parsing of `Content-Length` could allow request smuggling
Date:          2021-07-07
ID:            RUSTSEC-2021-0078
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0078
Solution:      Upgrade to >=0.14.10
Dependency tree:
hyper 0.14.4
├── shiplift 0.7.0
│   └── enclave_build 0.1.0
│       └── nitro-cli 1.0.12
├── hyperlocal 0.8.0
│   └── shiplift 0.7.0
└── hyper-openssl 0.9.1
└── shiplift 0.7.0
Crate:         hyper
Version:       0.14.4
Title:         Integer overflow in `hyper`'s parsing of the `Transfer-Encoding` header leads to data loss
Date:          2021-07-07
ID: …
=> nitro-cli: Update version of hyper crate and Ignore tar crate advisory till fix is available

Cargo.lock, Makefile, THIRD_PARTY_LICENSES_RUST_CRATES.html
Fix the following error by updating to the latest version of the tar
crate:
Crate:         tar
Version:       0.4.26
Title:         Links in archive can create arbitrary directories
Date:          2021-07-19
ID:            RUSTSEC-2021-0080
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0080
Solution:      Upgrade to >=0.4.36
Dependency tree:
tar 0.4.26
└── shiplift 0.7.0
└── enclave_build 0.1.0
└── nitro-cli 1.0.12
=> nitro-cli: Update version of tar crate

Cargo.lock, Cargo.toml, THIRD_PARTY_LICENSES_RUST_CRATES.html, src/common/commands_parser.rs, src/lib.rs, src/main.rs, src/utils.rs, tests/integration/helpers.py, tests/integration/test_commands.py, tests/test_nitro_cli_args.rs, tests/tests.rs
Resolves #229
Add `--disconnect-timeout` option to console subcommand.
Add cli argument tests and integration tests for the `--disconnect-timeout` option.
=> Add `--disconnect-timeout` option to console subcommand

SPECS/aws-nitro-enclaves-cli.spec, bootstrap/nitro-cli-config
This fixes https://github.com/aws/aws-nitro-enclaves-cli/issues/227.
The correct ownership of the "/dev/nitro_enclaves" file should be
root:ne. This ownership change may not occur immediately upon
triggering the udev rule is, effectively preventing a non-root user
from interacting with enclaves until either the change occurs or
the instance gets rebooted. Therefore, we use 'chgrp' to force the
correct group ownership change from the start.
Signed-off-by: Andrei Trandafir <aatrand@amazon.com>
=> nitro-cli: Set correct group ownership for /dev/nitro_enclaves

Cargo.lock, Cargo.toml, eif_defs/src/lib.rs, eif_utils/Cargo.toml, eif_utils/src/bin/eif_build.rs, eif_utils/src/lib.rs, src/common/document_errors.rs, src/common/json_output.rs, src/common/mod.rs, src/enclave_proc/commands.rs, src/enclave_proc/mod.rs, src/enclave_proc/resource_manager.rs, src/enclave_proc/utils.rs, src/lib.rs, src/main.rs, tests/integration/helpers.py, tests/integration/test_commands.py, tests/test_nitro_cli_args.rs, tests/tests.rs
PCRs are now computed when running the enclave not only when building the EIF. The values are saved in the EnclaveManager and printed when executing describe-enclaves.
Computation is done by a thread spawned when starting the enclave and completed by waiting the thread when calling the first describe.
Previous output format:
```
$ ./nitro-cli run-enclave --cpu-count 2 --memory 256 --enclave-cid 16 --eif-path hello-signed.eif --debug-mode
Start allocating memory...
Started enclave with enclave-cid: 16, memory: 256 MiB, cpu-ids: [2, 10]
{
"EnclaveID": "i-0584873aac8fea23b-enc17ad2edcbfdad4b",
"ProcessID": 95271,
"EnclaveCID": 16,
"NumberOfCPUs": 2,
"CPUIDs": [
2,
10
],
"MemoryMiB": 256
}
ubuntu@ip-172-31-46-66:~/aws-nitro-enclaves-cli/target/release$ ./nitro-cli describe-enclaves
[
{ …
```
=> PCR describe

Cargo.lock, eif_defs/Cargo.toml, eif_defs/src/lib.rs, eif_utils/src/lib.rs
Added EifSectionMetadata to the EifSectionType enum. The
purpose is to use it in eVMM to update the EIF version.
V4 will contain the metadata section added the with the
`build-enclaves` command.
Also added Metadata struct for (de)serializing the EIF section
in eVMM. Currently treating EifSectionMetadata as an invalid
section in EifReader until we merge the rest of the metadata
implementation.  
=> eif_defs: Add new metadata EIF section type

SPECS/aws-nitro-enclaves-cli.spec
Since the spec file doesn't support a list for the BuildArch
tag, set it as noarch, as if the build it's supported by any
architecture. Limit the build architectures with the ExclusiveArch tag.
More details here: [](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_spec_files)
Signed-off-by: George-Aurelian Popescu <popegeo@amazon.com>
=> Add support for aarch64 rpm with koji

SPECS/aws-nitro-enclaves-cli.spec
If the BuildArch tag is not set, the package automatically
inherits the Architecture of the machine on which is built.
Signed-off-by: popegeo <popegeo@amazon.com>
=> Remove BuildArch from spec file

docs/image_signing.md
The AWS Nitro Enclaves COSE crate codebase has been moved to its own
GitHub repository.
Update the COSE references from the image signing docs to point to this
GitHub repository.
=> docs: Update references to the AWS Nitro Enclaves COSE crate

README.md, docs/centos_stream_8_how_to_install_nitro_cli_from_github_sources.md, docs/fedora_34_how_to_install_nitro_cli_from_github_sources.md, docs/rhel_8.4_how_to_install_nitro_cli_from_github_sources.md, docs/ubuntu_20.04_how_to_install_nitro_cli_from_github_sources.md
Add docs which include options of how to install Nitro CLI from
GitHub sources on a set of Linux distros.
=> docs: Add refs for Nitro CLI install from sources on a set of Linux distros

Makefile
Nitro-cli build checks if the files under src are modified.
It does not check for the enclave_build crate. As a result,
the "make nitro-cli" command would not build a new version
of nitro-cli with modified enclave_build.
Given that enclave_build is part of the build command,
extend the make rules to capture those changes.
Signed-off-by: Alexandru Vasile <lexnv@amazon.com>
=> build: Extend nitro-cli build with enclave_build source

src/common/commands_parser.rs, src/common/document_errors.rs, src/common/json_output.rs, src/common/mod.rs, src/enclave_proc/commands.rs, src/enclave_proc/connection.rs, src/enclave_proc/cpu_info.rs, src/enclave_proc/mod.rs, src/enclave_proc/resource_manager.rs, src/enclave_proc/utils.rs, src/lib.rs, src/main.rs, tests/integration/helpers.py, tests/integration/test_commands.py, tests/test_nitro_cli_args.rs, tests/tests.rs
Introducing a new option for the `run-enclaves` command allowing users to set custom names for running enclaves instead of using only the ID. The name is set following the option `--enclave-name` and will be uniquely assigned to each of the running enclaves. In case of name conflicts, an index will be concatenated to the initial name, incrementing until the name becomes unique. This action is optional and if no name is provided, the EIF name will take its place.
The name will be part of the output of the following commands: `run-enclave`, `describe-enclaves` and `terminate-enclave`.
Commands that use the ID for targeting a specific enclave, now have the option to address the enclave by its name. So the commands `console` and `terminate-enclave` will have the option to use `--enclave-name` …
=> Named enclaves

vsock_proxy/README.md
Update the location of the vsock proxy configuration file in the vsock
proxy README, to match the current location.
*Issue #303*
=> vsock_proxy/README: Update vsock proxy configuration file location

enclave_build/src/docker.rs, run_tests.sh, tests/integration/helpers.py, tests/tests.rs
Update the tests that use the vsock sample to include Arm support. The
vsock sample is the one that can be found at:
https://github.com/aws/aws-nitro-enclaves-samples/tree/main/vsock_sample/rs
=> tests: Update vsock sample tests for Arm support

run_tests.sh, src/common/commands_parser.rs, src/lib.rs, src/main.rs, src/utils.rs, tests/integration/helpers.py, tests/integration/test_commands.py, tests/test_nitro_cli_args.rs, tests/tests.rs
New command for getting the PCR value from an input file. Currently takes two types of arguments with the options: `--input` a general use to hash all the bytes from a file and `--signing-certificate` for retrieving PCR8 from a .pem file. The second type in particular, performs additional serialisation of a DER-encoded structure before hashing the content.
The purpose of the command is to identify the certificate used to sign a certain EIF, by finding the PCR8 and comparing it to the build measurement of the EIF.
Output:
```
$ ./nitro-cli pcr --signing-certificate cert.pem
{
"PCR8": "e6eb66339de75e8ed2939e9524cba83aa96f2c79eaf5d5ac3bacf2cb76c75a31f983d0b80f55b29f0acd256b8cff1999"
}
$ ./nitro-cli build-enclave --docker-uri hello:latest --output-file hello-sample-signed.eif --private-key …
```
=> NitroCLI `pcr` command

eif_utils/src/lib.rs, src/common/document_errors.rs, src/common/mod.rs, src/enclave_proc/commands.rs
To avoid ambiguous errors for invalid signed EIFs, `run-enclave` command extracts the signature section from the image and performs certificate validation. It checks the .pem format of the certificate, the signature against the public key and if the certificate is expired.
Suggestive error messages along with a new error code have been added to make the output more explicit.
Output:
```
$ ./nitro-cli run-enclave --cpu-count 2 --memory 256 --eif-path hello-expired.eif 
[ E59 ] Signature checker error. Such error appears when validation of the signing certificate fails.
For more details, please visit https://docs.aws.amazon.com/enclaves/latest/user/cli-errors.html#E59
If you open a support ticket, please provide the error log found at …
```
=> run-enclave: Verify signing certificate

drivers/virt/nitro_enclaves/ne_misc_dev.c
nitro_enclaves: Use get_user_pages_unlocked() call to handle mmap assert
After commit 5b78ed24e8ec ("mm/pagemap: add mmap_assert_locked()
annotations to find_vma*()"), the call to get_user_pages() will trigger
the mmap assert.
static inline void mmap_assert_locked(struct mm_struct *mm)
{
lockdep_assert_held(&mm->mmap_lock);
VM_BUG_ON_MM(!rwsem_is_locked(&mm->mmap_lock), mm);
}
[   62.521410] kernel BUG at include/linux/mmap_lock.h:156!
...........................................................
[   62.538938] RIP: 0010:find_vma+0x32/0x80
...........................................................
[   62.605889] Call Trace:
[   62.608502]  <TASK>
[   62.610956]  ? lock_timer_base+0x61/0x80
[   62.614106]  find_extend_vma+0x19/0x80
[   62.617195]  __get_user_pages+0x9b/0x6a0
[   62.620356] …
=> nitro_enclaves: Use get_user_pages_unlocked() call to handle mmap assert

README.md
Update the section about using the Nitro Enclaves CLI to include
references about the available packages for it.
Remove the "How to install (Amazon Linux repository)" section as this
info is available in the AWS docs referenced in the "How to use"
section.
=> README: Update "How to use" section to add refs for package availability

docs/ubuntu_20.04_how_to_install_nitro_cli_from_github_sources.md
Remove the additional whitespace from a "ls" command in the Ubuntu
documentation for installing Nitro CLI from GitHub sources.
=> docs: Remove additional whitespace from a "ls" command in Ubuntu docs

bootstrap/nitro-enclaves-allocator
Fix the comment that refers to the configuration file to mention the
up-to-date one: /etc/nitro_enclaves/allocator.yaml.
*Issue #353*
=> nitro-enclaves-allocator: Update comment about allocator config file

Cargo.lock, THIRD_PARTY_LICENSES_RUST_CRATES.html
Fix the following error by updating to the latest version of the regex
crate:
Crate:         regex
Version:       1.5.4
Title:         Regexes with large repetitions on empty sub-expressions take a very long time to parse
Date:          2022-03-08
ID:            RUSTSEC-2022-0013
URL:           https://rustsec.org/advisories/RUSTSEC-2022-0013
Solution:      Upgrade to >=1.5.5
Dependency tree:
regex 1.5.4
├── flexi_logger 0.15.12
│   └── nitro-cli 1.2.0
├── env_logger 0.9.0
├── env_logger 0.7.1
└── bindgen 0.59.2
└── nitro-cli 1.2.0
*Issue #359*
=> nitro-cli: Update version of regex crate

Cargo.lock, THIRD_PARTY_LICENSES_RUST_CRATES.html
Run "cargo update" in the root directory of the Nitro CLI repository to
update the crates dependencies of the nitro-cli to the latest version.
=> nitro-cli: Update crates dependencies to the latest version

eif_utils/src/identity.rs
The restrictions on string values and flat structure was unnecessary and is removed.
Example output:
```
$> cat custom.json
{
"AppVersion": "3.0",
"TestField": "Some info",
"CustomInfo": "Added by user",
"ArrayField": [
{
"id": 0,
"name": "Value0"
},
{
"id": 1,
"name": "Value1"
},
{
"id": 42,
"name": "Value42"
}
]
}
$> nitro-cli build-enclave --docker-uri hello:latest --output-file hello.eif --name="my_image" --version="3.35" --metadata custom.json
Start building the Enclave Image...
Using the locally available Docker image...
Enclave Image successfully created.
{
"Measurements": {
"HashAlgorithm": "Sha384 { ... }",
"PCR0": "a0a09ef11c121dc943bb41bd60219f367847b667992c7a9c38969f5b2b5afcd9b8dd5c7471f1c14965f06ae13798275e",
"PCR1": …
```
=> nitro-cli: Remove custom metadata structure restriction for EIF images

samples/command_executer/README.md
command-executor.eif has a underscore instead of hyphen.
nitro-cli command is resolvable at the prompt, no need to include './'
=> Typos in the step-4 nitro-cli run-enclave command

samples/command_executer/README.md
#364
Use root makefile to build `command-execute`r binary and EIF image
=> docs: Update README for command-executer sample

enclave_build/src/lib.rs, third_party/linuxkit/README.md
https://github.com/aws/aws-nitro-enclaves-cli/issues/235
Linuxkit blobs are updated from the upstream branch
with commit `b710224cdf9a8425a7129cdcb84fc1af00f926d7`
The blob is slightly modified to support prefixing the
filesystem of the docker image. This is necessary for
generating the initrd image.
To avoid size limitations present in the linux kernel,
the gzip wrapper is removed.
=> linuxkit: Update linuxkit blobs to v0.8+

enclave_build/src/docker.rs
https://github.com/aws/aws-nitro-enclaves-cli/issues/235
`shiplift` library parses `DOCKER_HOST` environment variable internally.
User can forward it to another docker-compatible URL
(`unix:///var/run/docker.sock` by default).
Wrapper code we used around `shiplift` is redundant and repeats `shiplift`'s
internal implementation but without considering that specified URL
can point to any unix socket in a format of `unix:///socket/path`
=> shiplift: Proper usage of DOCKER_HOST env variable

bootstrap/nitro-enclaves-allocator
*Issue #, if available:* N/A
When compiling the project, `NITRO_CLI_INSTALL_DIR` is used to direct where to copy and install the relevant files. In the [Ubuntu compilation guide](https://github.com/aws/aws-nitro-enclaves-cli/blob/main/docs/ubuntu_20.04_how_to_install_nitro_cli_from_github_sources.md), it is set as `NITRO_CLI_INSTALL_DIR=/`. 
At Stripe, we compile EIFs using `nitro-cli` in our CI systems and run EIFs via `nitro-cli` on other hosts. The directory layout of the nitro-cli tooling is different in CI than it is on our live systems. We've been setting `NITRO_CLI_INSTALL_DIR` to handle this. For example, `NITRO_CLI_INSTALL_DIR=/build` in CI and `NITRO_CLI_INSTALL_DIR=/deploy` when it is deployed on our live hosts. 
We encountered an issue in doing this …
=> Allow NITRO_CLI_INSTALL_DIR be set for path to allocator.yaml

Makefile
*Issue #, if available:* N/A
*Description of changes:* Similar to https://github.com/aws/aws-nitro-enclaves-cli/pull/376, there are a few cases where `NITRO_CLI_INSTALL_DIR` is fixed to a particular path when it should be adjustable. In this case, when compiling `aws-nitro-enclaves-cli`, the makefile command 
```
sed -i "2 a NITRO_CLI_INSTALL_DIR=$$(readlink -f ${NITRO_CLI_INSTALL_DIR})" \
${NITRO_CLI_INSTALL_DIR}${ENV_SETUP_DIR}/nitro-cli-env.sh
```
injects the current `NITRO_CLI_INSTALL_DIR` value to the `nitro-cli-env.sh` file. 
At Stripe, we compile `aws-nitro-enclaves-cli` from source in CI and later deploy the binaries and configuration files to live hosts. The `NITRO_CLI_INSTALL_DIR` is different in our CI systems than it is on our live hosts. For example, …
=> Allow NITRO_CLI_INSTALL_DIR to be overriden in nitro-cli-env.sh

.github/workflows/summary.yml
github.event is empty in case of sceduled workflows.
Repository name should be fetched through github.repository variable instead.
=> workflows: fix repository name in summary

drivers/virt/nitro_enclaves/Kconfig, drivers/virt/nitro_enclaves/ne_misc_dev.c, drivers/virt/nitro_enclaves/ne_misc_dev_test.c
The kunit_test_suite() macro previously conflicted with module_init,
making it unsuitable for use in the nitro_enclaves test. Now that it's
fixed, we can use it instead of a custom call into internal KUnit
functions to run the test.
As a side-effect, this means that the test results are properly included
with other suites when built-in. To celebrate, enable the test by
default when KUNIT_ALL_TESTS is set (and NITRO_ENCLAVES enabled).
The nitro_enclave tests can now be run via kunit_tool with:
./tools/testing/kunit/kunit.py run --arch=x86_64 \
--kconfig_add CONFIG_PCI=y --kconfig_add CONFIG_SMP=y \
--kconfig_add CONFIG_HOTPLUG_CPU=y \
--kconfig_add CONFIG_VIRT_DRIVERS=y \
--kconfig_add CONFIG_NITRO_ENCLAVES=y \
'ne_misc_dev_test'
(This is a pretty long command, so it may be worth adding a …
=> nitro_enclaves: test: Use kunit_test_suite() macro

Cargo.toml, README.md, driver-bindings/Cargo.toml, eif_loader/Cargo.toml, enclave_build/Cargo.toml, samples/command_executer/Cargo.toml, tools/Dockerfile1804.aarch64, tools/Dockerfile1804.x86_64, vsock_proxy/Cargo.toml
Crates with edition 2021 were not compiling because support for this edition was added with Rust 1.56
- Updated RUST_VERSION ENV variable to 1.58.1 in aarch64 and x86_64 Dockerfiles
- Added Rust version 1.58 to all Cargo.toml files
- Added MSRV 1.58.1 badge to README
=> Update Rust version to 1.58.1

eif_loader/src/lib.rs
error: you are deriving `PartialEq` and can implement `Eq`
--> eif_loader/src/lib.rs:21:17
|
21 | #[derive(Debug, PartialEq)]
|                 ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
|
note: the lint level is defined here
--> eif_loader/src/lib.rs:3:9
|
3  | #![deny(warnings)]
|         ^^^^^^^^
= note: `#[deny(clippy::derive_partial_eq_without_eq)]` implied by `#[deny(warnings)]`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
error: could not compile `eif_loader` due to previous error
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> eif_loader: Fix clippy warning (clippy::derive_partial_eq_without_eq)

Makefile, src/enclave_proc/cpu_info.rs, tools/Dockerfile1804.aarch64, tools/Dockerfile1804.x86_64
To allow cpu_info unit tests to run even on systems without Nitro
Enclaves, or with Nitro Enclaves in a different configuration, allow
reading CpuInfo from a BufRead, to mock the expected output.
=> cpu_info: mock input in unit tests

drivers/virt/nitro_enclaves/Kconfig
Both the USB4 and Nitro Enclaves KUNIT tests are now able to be compiled if KUNIT is compiled as a module. This leads to issues if KUNIT is being packaged separately from the core kernel and when KUNIT is run baremetal without the required driver compiled into the kernel.
Fixes: 635dcd16844b ("thunderbolt: test: Use kunit_test_suite() macro")
Fixes: fe5be808fa6c ("nitro_enclaves: test: Use kunit_test_suite() macro")
Signed-off-by: Nico Pache <npache@redhat.com>
Reviewed-by: David Gow <davidgow@google.com>
Reviewed-by: Andra Paraschiv <andraprs@amazon.com>
Acked-by: Brendan Higgins <brendanhiggins@google.com>
Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> kunit: fix Kconfig for build-in tests USB4 and Nitro Enclaves

Cargo.lock, Cargo.toml, SPECS/aws-nitro-enclaves-cli.spec, THIRD_PARTY_LICENSES_RUST_CRATES.html, sources
Update the nitro-cli version to 1.2.1 for a new release.
=> nitro-cli: Update Cargo.lock/.toml and RPM spec for 1.2.1 release

SPECS/aws-nitro-enclaves-cli.spec
The Rust version has been updated to 1.58 in the Cargo.toml files for nitro-cli.
Modify the minimum required Rust version in the spec file to be 1.58.
=> aws-nitro-enclaves-cli.spec: Update minimum required Rust version

Cargo.lock, enclave_build/Cargo.toml, enclave_build/src/docker.rs, enclave_build/src/lib.rs
Dockerless frature (1/5)
This is the first PR from splitting the initial one #404.
To avoid defining error types in each module file to be implemented for this feature, I created a general error type in the `lib.rs` file. In this way, the enclave build error can be used outside the crate and also extended easier.
By using `thiserror` attributes, we don't need display implementations for every defined error.
=> enclave_build: Error refactor

enclave_build/src/lib.rs
warning: the borrowed expression implements the required traits
--> enclave_build/src/lib.rs:221:19
|
221 |               .args(&[
|  ___________________^
222 | |                 "build",
223 | |                 "-name",
224 | |                 &bootstrap_ramfs,
...   |
227 | |                 ramfs_config_file.path().to_str().unwrap(),
228 | |             ])
| |_____________^
|
= note: `#[warn(clippy::needless_borrow)]` on by default
warning: the borrowed expression implements the required traits
--> enclave_build/src/lib.rs:241:19
|
241 |               .args(&[
|  ___________________^
242 | |                 "build",
243 | |                 "-docker",
244 | |                 "-name",
...   |
250 | |                 ramfs_with_rootfs_config_file.path().to_str().unwrap(),
251 | | …
=> enclave_build: Fix clippy warning (clippy::needless_borrow)

.github/workflows/ci.yml, run_tests.sh
Currently all the workflows are being run in a private environment and the results from this workflow are not being published, which makes it difficult for contributors to understand and fix the issues they might encounter. This adds a separate CI for build, format and clippy, which should add at least some observability. Some of the tests require a specific environment to run, so currently they cannot be enabled to run in the github workflow, I will filter out these tests separately and either fix them, where possible, or filter them out from the list of tests to run in the workflow in a future PR.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
=> ci: add workflows build, clippy and format workflows

bootstrap/nitro-enclaves-allocator
The parsing logic from the nitro-enclaves-allocator script doesn't work properly when a different language than English is set in the locale configuration (e.g. /etc/locale.conf).
Set the language to English in the nitro-enclaves-allocator script to fix this possible issue.
*Issue #428*
=> nitro-enclaves-allocator: Set local language to English

enclave_build/src/docker.rs, src/utils.rs
error: the borrowed expression implements the required traits
--> enclave_build/src/docker.rs:101:50
|
101 |                     let decoded = base64::decode(&auth).map_err(|err| {
|                                                  ^^^^^ help: change this to: `auth`
|
= note: `-D clippy::needless-borrow` implied by `-D warnings`
Signed-off-by: Alexandru Ciobotaru <alcioa@amazon.com>
=> clippy: fix minor issue

enclave_build/docs/storage.md, enclave_build/src/image.rs, enclave_build/src/lib.rs, enclave_build/src/storage.rs
OCI storage
Implemented an OCI compliant storage for pull and inspect operations. This storage can be directly used by `linuxkit` as its own cache, preventing it to pull the images again. The structure of the storage directory is as follows:
```
storage_dir/
|________index.json        -> points to the manifest blob for each image
|________oci-layout
|            blobs/sha256/
|            |_______manifest_hash  -> points to config and layers
|            |_______config_hash
|            |_______layer_hash
```
The storage module supports store and fetching operations. The first fetch validates the files for the requested image and loads the config in the memory (the following fetches will use this config). Only one config is stored as we do not need to keep track of all the stored images …
=> OCI storage

ci_entrypoint.sh, run_tests.sh
It's not recommended to use get-login anymore, since the temporary password is printed out.
=> CI: use get-login-password instead of get-login

enclave_build/src/docker.rs, enclave_build/src/image.rs, enclave_build/src/image_manager.rs, enclave_build/src/lib.rs, enclave_build/src/storage.rs
Image Manager
The image manager trait exposes the operations required for building the EIF. The decision wether to fetch the image details from the local OCI storage or if they should be pulled from a registry is implemented as a failover logic that will allow the build to continue even if the image is missing locally, the storage is corrupt or missing.
The same manager trait will be used for building EIFs from Docker images but will be adapted in a future PR with the implied workflow changes in `lib.rs`.
=> enclave_build: Image manager trait

enclave_build/src/docker.rs, run_tests.sh, tests/integration/helpers.py, tests/tests.rs
In tests we were using a private container that was not possible to use without credentials owned by the aws-nitro-enclaves team. This commit uses instead a container image that is public, and should make running the tests on just a Nitro Enclaves instance easier.
There are still some issues with running tests, in the sense that the integration tests expect to be run after run_tests creates some enclave images and sets up the environment, but run_tests script expects to be able to do insmod and rmmod, which on standard Amazon Linux is not possible, since the module is built-in and cannot be replaced, so it will fail.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> replace private containers with public containers in tests

.github/dependabot.yml
In order to no get flooded with PRs from dependabot daily, let's check for new versions weekly instead.
=> update dependabot to open PRs weekly

src/enclave_proc_comm.rs
Removed useless `vec!` macro
* Issue
```
14:40 $ cargo clippy --all
Checking eif_loader v0.1.0 (/tmp/aws-nitro-enclaves-cli/eif_loader)
Checking enclave_build v0.1.0 (/tmp/aws-nitro-enclaves-cli/enclave_build)
Checking driver-bindings v0.1.0 (/tmp/aws-nitro-enclaves-cli/driver-bindings)
Checking vsock-proxy v0.1.0 (/tmp/aws-nitro-enclaves-cli/vsock_proxy)
Checking nitro-cli v1.2.2 (/tmp/aws-nitro-enclaves-cli)
error: useless use of `vec!`
--> src/enclave_proc_comm.rs:193:22
|
193 |     let mut events = vec![EpollEvent::empty(); 1];
|                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: you can use an array directly: `[EpollEvent::empty(); 1]`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_vec
note: the lint level is defined …
```
=> Fix clippy error useless_vec

Cargo.lock
CI failure.
Update **proc-macro2**'s version from **1.0.56** to **1.0.67**.
Update **openssl** from **0.10.51** to **0.10.55** to fix RUSTSEC-2023-0044 warning.
=> cargo.lock: version bump

SPECS/aws-nitro-enclaves-cli.spec
The package builder used for Amazon Linux 2023 mangles shebangs in the packaged scripts, but the new paths may not exist. For example, in the case of `hello.sh`, the shebang is rewritten from `#!/bin/sh` to `#!/usr/bin/sh`, but the latter path does not exist. This has the effect of preventing the "Hello Enclave" enclave from being instantiated. Therefore we disable shebang mangling for the entire package.
=> SPECS/aws-nitro-enclaves-cli.spec: Do not mangle shebangs

run_tests.sh
The `connection_test` test runs the vsock-proxy on the parent instance for testing the connection between a server and a client on the same instance, in which case the vsock loopback must be enabled on the parent instance.
=> run_tests.sh: Load vsock_loopback module for vsock-proxy tests

drivers/virt/nitro_enclaves/ne_misc_dev.c
The `topology_core_id(cpu)` function, which generates the core id used for splitting the CPU pool and indexing `ne_cpu_pool.avail_threads_per_core`, return different values depending on the architecture on which it is run.
To address this problem, this commit removes the dependency on `topology_core_id` and modifies the logic for splitting the cpu pool. Now, `topology_sibling_cpumask` is called for each cpu. If a cpu has not yet been added to `ne_cpu_pool.avail_threads_per_core`, its siblings are checked to see if they are part of the cpu pool and have not yet been added. If so, they are added to the corresponding core.
This change ensures that the cpu pool is properly split and indexed regardless of the architecture.
By submitting this …
=> Remove dependency on topology_core_id for splitting cpu pool

run_tests.sh, samples/command_executer/Cargo.toml, samples/command_executer/src/lib.rs
Currently the `run_describe_terminate_command_executer_docker_image` test fails when using the deprecated SockAddr dependency because the console output of the enclave under test is not entirely captured. Fortunately, switching to VsockAddr fixes that.
=> command-executer: Replace deprecated SockAddr with VsockAddr

samples/command_executer/src/lib.rs
Previous changes overlooked the fact that imports have to be sorted alphabetically.
=> command-executer: Fix order to Rust imports

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, samples/command_executer/Cargo.toml, samples/command_executer/src/command_parser.rs, samples/command_executer/src/lib.rs, samples/command_executer/src/protocol_helpers.rs
=> Revisit the command-executer workspace

Cargo.lock, Cargo.toml, SPECS/aws-nitro-enclaves-cli.spec, THIRD_PARTY_LICENSES_RUST_CRATES.html, sources
Update the nitro-cli version to 1.2.3 for a new release.
=> Prepare 1.2.3 release

.github/workflows/ci.yml, .github/workflows/license_update.yml, .github/workflows/summary.yml, Cargo.toml, README.md, SPECS/aws-nitro-enclaves-cli.spec, driver-bindings/Cargo.toml, eif_loader/Cargo.toml, enclave_build/Cargo.toml, samples/command_executer/Cargo.toml, src/common/mod.rs, src/enclave_proc/connection.rs, src/enclave_proc/resource_manager.rs, tools/Dockerfile, vsock_proxy/Cargo.toml
=> Update MSRV to 1.68.2

vsock_proxy/README.md, vsock_proxy/service/nitro-enclaves-vsock-proxy.service
Initially, logging was disabled by default for the vsock service. This change enables warning and error logs, allowing easier troubleshooting of connectivity issues.
=> vsock_proxy: set log level to warn

Cargo.lock, src/enclave_proc/socket.rs, vsock_proxy/Cargo.toml
=> deps: update dns-lookup and inotify

Cargo.lock, enclave_build/Cargo.toml, enclave_build/src/docker.rs, enclave_build/src/lib.rs, enclave_build/src/utils.rs, src/common/mod.rs, tools/Dockerfile
The `shiplift` crate is outdated and incompatible with Docker 25. This PR replaces the it with `bollard`, allowing `nitro-cli` to work with Docker version 25 and newer.
Special thanks to @jalaziz for their contribution.
=> Replace shiplift with bollard for Docker 25+ compatibility

Cargo.lock, Cargo.toml, samples/command_executer/Cargo.toml
The num-derive crate version 0.3 is no longer compatible with the current nightly Rust toolchain. Upgrading to version 0.4 to ensure compatibility and allow successful builds.
=> cargo: Upgrade num-derive to v0.4

Cargo.lock
Update Cargo.lock to use the following crate versions:
- quote: downgraded from 1.0.36 to 1.0.35
- async-trait: downgraded from 0.1.80 to 0.1.79
- time: downgraded from 0.3.36 to 0.3.34
These crate versions are downgraded to ensure compatibility with some other dependencies and avoid potential issues.
=> fix(deps): downgrade crate versions due to compatibility issues

Cargo.lock, Cargo.toml, SPECS/aws-nitro-enclaves-cli.spec, THIRD_PARTY_LICENSES_RUST_CRATES.html
This commit updates the following files to prepare for the v1.3.0 release:
- Cargo.lock
- Cargo.toml
- aws-nitro-enclaves-cli.spec
- THIRD_PARTY_LICENSES_RUST_CRATES.html
=> Prepare for Release v1.3.0

src/enclave_proc/resource_manager.rs, src/lib.rs
Resolving a couple of clippy errors when building with Rust 1.78:
* https://rust-lang.github.io/rust-clippy/master/index.html\#/unnecessary_get_then_check
* https://rust-lang.github.io/rust-clippy/master/index.html\#/unnecessary_to_owned
* https://rust-lang.github.io/rust-clippy/master/index.html\#/to_string_trait_impl
=> clippy: resolve build errors for Rust 1.78

vsock_proxy/src/dns.rs
This commit changes the DNS resolver's initialization to use the system's configured nameservers instead of the default nameserver provided by hickoery-resolver crate.
The `Resolver::from_system_conf()` method is now used to initialize the DNS resolver. This method attempts to read the system's nameserver configuration, which may come from various sources such as `/etc/resolv.conf`.
=> vsock_proxy: Use system-configured nameservers for DNS resolution

Cargo.lock, Cargo.toml, SPECS/aws-nitro-enclaves-cli.spec, THIRD_PARTY_LICENSES_RUST_CRATES.html, sources, vsock_proxy/Cargo.toml, vsock_proxy/src/main.rs
- vsock-proxy: Bump version to 1.0.1
- vsock_proxy: Use system-configured nameservers for DNS resolution
- Update init blob to support user namespaces
- clippy: resolve build errors for Rust 1.78
=> Prepare for Release v1.3.1

scripts/lib_tests.sh, scripts/run_tests.sh
**Issue #, if available:** -
```
scripts/run_tests.sh: Add check dependencies
Check that all the dependencies to run the test script are in place and bail out early before spending time on needless work.
The dependencies are:
* running as root
* docker has to function
* pytest-3 needs to be installed
```
When testing builds for https://github.com/aws/aws-nitro-enclaves-sdk-bootstrap/pull/28 I struggled through some hardships with the dependencies needed to run the test scripts. Let's make this easier for the next person by bailing out early if dependencies are not met.
**Testing done:**
Tested all cases starting from a vanilla Ubuntu instance running without root privileges, adding another dependency with each iteration.
By submitting this pull request, I …
=> scripts/run_tests.sh: Add check dependencies

enclave_build/src/lib.rs, enclave_build/src/yaml_generator.rs
**Issue #, if available:** -
Pull in updated linuxkit binaries, built reproducibly from https://github.com/aws/aws-nitro-enclaves-sdk-bootstrap/commit/d55087f7f405a21220f22ced2ea9b7a438544ee0
```
blobs: Update linuxkit binaries to version based on v1.2.0
The linuxkit blobs provided as part of this repository have been a sore
point with regards to how these are built and where they come from. This
updates them to a new version that is based on top of the latest
upstream release v1.2.0 and can be reproducibly build from
aws-nitro-enclaves-sdk-bootstrap d55087f7f405 [0].
With the update linuxkit has changed the format of its command line
options from the -<option> format to the --<option> format.
Further, linuxkit introduced functionality to add an SBOM file with …
```
=> blobs: Update linuxkit binaries to version based on v1.2.0

samples/command_executer/src/lib.rs, src/common/commands_parser.rs, src/utils.rs
Resolving clippy error when building with Rust 1.79: https://rust-lang.github.io/rust-clippy/master/index.html#/legacy_numeric_constants
=> clippy: resolve build errors for Rust 1.79

src/enclave_proc/resource_manager.rs
Before pull request #310 the enlave boot timeout was calculated based on the allocated memory size. We reintroduce this heuristic in addition to the heuristic based on the eif size, since we observed timeout violations for large allocated memory sizes.
=> nitro-cli: Update enclave boot timeout based on allocated memory

sources
Release 1.3.2 [1] misses OpenSSL dependency update for RPM spec [2]
[1]: https://github.com/eugkoira/aws-nitro-enclaves-cli/commit/f31ce847c930a13558b72c837329b8e635000b44
[2]: https://github.com/eugkoira/aws-nitro-enclaves-cli/commit/b7bdad82729f6ee03fbe788e7a1ffd708d97284d
=> Update sources for 1.3.2 release

Cargo.lock, src/common/commands_parser.rs, src/common/document_errors.rs, src/common/mod.rs, src/lib.rs, src/main.rs, tests/test_nitro_cli_args.rs, tests/tests.rs
#204 
This PR allows to sign pre-built EIFs using the new `sign-eif` command. Users can use either a local private key, or a KMS key.
=> Sign EIFs separately

Cargo.lock, Cargo.toml, SPECS/aws-nitro-enclaves-cli.spec, THIRD_PARTY_LICENSES_RUST_CRATES.html, sources
Update nitro-cli version to 1.4.0
=> Prepare 1.4.0 release

samples/command_executer/src/protocol_helpers.rs
The command_executer/src/protocol_helpers.rs has a denial of service bug. The `recv` method may return 0 bytes (the `size`) variable, and this case is not accounted for: the 0 may be added to the `recv_bytes` infinitely.
Similar issue exists in vsock_sample: https://github.com/aws/aws-nitro-enclaves-samples/blob/dc4bba3d99bc4988a87ce7775cf1bc554537da16/vsock_sample/rs/src/protocol_helpers.rs#L45-L52
Correct handling is implemented in python versions and in the kmstool: https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/550f7313bf792bf03200c7c6e1ac3fd7d2dc382f/bin/kmstool-enclave/main.c#L245-L247
=> command_executer - recv infinite loop

Cargo.lock, Cargo.toml, SPECS/aws-nitro-enclaves-cli.spec, THIRD_PARTY_LICENSES_RUST_CRATES.html, sources
Update nitro-cli version to 1.4.2.
- bump ring from 0.17.13 to 0.17.14
=> Prepare 1.4.2 release

vsock_proxy/src/proxy.rs
At this moment for every item in allowlist that doesn't match with required host `vsock-proxy` will generate a warning.
Change it to only show warning if no matches were found.
=> Reduce warnings for vsock-proxy matching logic

Cargo.lock, enclave_build/Cargo.toml
When https://github.com/aws/aws-nitro-enclaves-cli/pull/595 merged, it caused a regression when using docker with TLS. By default `shiplift` is built with TLS support by default whereas bollard isn't.
=> Fix regression when using docker API with TLS
