README.md

Clarifies the installation guide.

README: improve installation guide

---

src/common/document_errors.rs

common: use correct error landing page

---

docs/image_signing.md

Signed-off-by: Alexandra Pirvulescu <alexprv@amazon.com>

docs: Fix links to rust-cose and eif-defs crates

---

drivers/virt/nitro_enclaves/ne_misc_dev.c

Simplify the logic of setting the mask result of the poll function.

nitro_enclaves: Simplify logic of the poll mask setup

---

SPECS/aws-nitro-enclaves-cli.spec

Updated the package revision to v6 and updated the changelog

cli: update spec file to reflect latest changes

---

SPECS/aws-nitro-enclaves-cli.spec

Updated the package revision to v7 and updated the changelog

cli: update spec file to reflect latest changes (v1.0-7)

---

tests/test_dev_driver.rs

Add a couple more tests for the enclave memory and CPUs that are handled
by the Nitro Enclaves kernel driver.

tests: Add more tests for the Nitro Enclaves kernel driver

---

third_party/linuxkit/LICENSE
third_party/linuxkit/README.md

Signed-off-by: Bogdan Neacsu <bnneacsu@amazon.com>
Issue #199 

Add third_party directory with linuxkit credit

---

THIRD_PARTY_LICENSES

Signed-off-by: Bogdan Neacsu <bnneacsu@amazon.com>

Add THIRD_PARTY_LICENSES file

---

Cargo.toml
SPECS/aws-nitro-enclaves-cli.spec

Included the latest changes in the SPEC file changelog
and updated the package version to 1.0-8.

SPEC: update package version to 1.0-8

---

THIRD_PARTY_LICENSES

Change the source code download link for the kernel tarball.
Signed-off-by: Bogdan Neacsu <bnneacsu@amazon.com>

Change download link from THIRD_PARTY_LICENSES

---

build.rs

This PR makes the nitro-cli build on ARM.
Signed-off-by: Laurentiu Stefan <stefala@amazon.com>

build: Make the build on ARM functional

---

SPECS/aws-nitro-enclaves-cli.spec

Replaces the post transaction scriptlet with a
trigger script which re-initializes the resources
only then the post-installation phase of package
v1.0-5 occurrs.
This indeed helps when the package is updated from
version 1.0-5 to whatever latest version might
be available at the update time (not necessarily the
consecutive release after 1.0-5).

SPEC: use a trigger script instead of %posttrans

---

SPECS/aws-nitro-enclaves-cli.spec

spec: Update spec file release to 1

---

Cargo.lock
Cargo.toml
eif_defs/Cargo.toml
eif_defs/src/eif_hasher.rs
eif_loader/Cargo.toml
eif_utils/Cargo.toml
eif_utils/src/lib.rs
enclave_build/Cargo.toml
enclave_build/src/docker.rs
run_tests.sh
tests/tests.rs

Update sha2 and shiplift crate dependencies

---

Makefile
THIRD_PARTY_LICENSES_RUST_CRATES.html
about.hbs
about.toml
run_tests.sh
tools/Dockerfile1804.x86_64

Add THIRD_PARTY_LICENSES_RUST_CRATES.html for Rust crates and check that it is always modified when changes are in order.

Rust licenses

---

README.md

Add info about the packages that need to be installed or updated in the
mentioned distros for the Nitro Enclaves kernel driver availability.

README: Add info about Nitro Enclaves kernel driver and distros packages

---

vsock_proxy/README.md

old command is no longer functioning
updated to the new command

Update vsock-proxy command in README.md

---

Cargo.lock
Cargo.toml
SPECS/aws-nitro-enclaves-cli.spec
THIRD_PARTY_LICENSES_RUST_CRATES.html
sources

Update release changes and vendorized dependencies in preparation for building a new rpm version.

Prepare for release 1.0.11-0

---

README.md

Include in the README a reference to the hello world example.
Update the info of the enclave image blobs to reflect the current
content from the Nitro Enclaves CLI repository.
*Issue #257*

README: Update README to match the current repository contents

---

Cargo.lock
Cargo.toml
SPECS/aws-nitro-enclaves-cli.spec
THIRD_PARTY_LICENSES_RUST_CRATES.html
sources

Do the necessary plumbing to release a new version of Nitro-cli

Prepare for releasing 1.0.12 version

---

README.md

These changes address the #241 inquiry about enclave disk space
Signed-off-by: Doru-Florin Blanzeanu <blanzed@amazon.com>
Description of changes:
Add enclave disk space documentation and how to configure.

README: Add enclave disk space information

---

THIRD_PARTY_LICENSES_RUST_CRATES.html
tools/Dockerfile1804.x86_64

Update the cargo-about crate to v0.3.0, the latest version.
Include the generated updates for the
THIRD_PARTY_LICENSES_RUST_CRATES.html file.

tools: Update cargo-about crate to the latest version

---

samples/command_executer/README.md

- Add note about production environment
- Modify commands parameters to follow the Makefile
Signed-off-by: Doru-Florin Blanzeanu <blanzed@amazon.com>
#228

command_executer: Update README to reflect current state

---

tests/test_dev_driver.rs

On Arm it is possible to start enclaves with an odd number of vCPUs.
Update the NE driver test that focuses on the enclave start scenarios
to include a setup with 1 vCPU, in addition to the one with 2 vCPUs.

tests: Add scenario of starting enclave with 1 vCPU on Arm

---

tests/integration/helpers.py
tests/integration/test_commands.py
tests/integration/test_installation.py

Apply python idiomatic concepts to increase the
pylint score of the modules.
`pylint3 ./tests/integration/helpers.py`
```
[Before] Your code has been rated at -2.28/10
[After]  Your code has been rated at 10.00/10
```
`pylint3 ./tests/integration/test_commands.py`
```
[Before] Your code has been rated at -3.08/10
[After]  Your code has been rated at 10.00/10
```
`pylint3 ./tests/integration/test_installation.py`
```
[Before] Your code has been rated at 0.00/10
[After]  Your code has been rated at 10.00/10
```
Pylint version: `pylint 2.10.0`

Pylint: List testing modules

---

tests/integration/test_commands.py

Add incremental timers to console timeout test
Signed-off-by: Costin-Robert Sin <costisin@amazon.com>

Modify console timeout test to remove hardcoded timer

---

README.md
drivers/virt/nitro_enclaves/Kconfig
drivers/virt/nitro_enclaves/ne_misc_dev.c
drivers/virt/nitro_enclaves/ne_pci_dev.c
drivers/virt/nitro_enclaves/ne_pci_dev.h
include/uapi/linux/nitro_enclaves.h

nitro_enclaves: Add support for Arm64 for the Nitro Enclaves kernel driver

---

build.rs
eif_defs/src/eif_hasher.rs
eif_utils/src/bin/eif_build.rs
eif_utils/src/lib.rs
enclave_build/src/lib.rs
enclave_build/src/main.rs
src/common/logger.rs
src/common/mod.rs
src/enclave_proc/mod.rs
src/enclave_proc/resource_manager.rs
src/enclave_proc/socket.rs
tests/test_dev_driver.rs
tests/tests.rs
vsock_proxy/src/starter.rs

Clippy fixes

---

drivers/virt/nitro_enclaves/Kconfig
drivers/virt/nitro_enclaves/ne_misc_dev.c
drivers/virt/nitro_enclaves/ne_misc_dev_test.c
drivers/virt/nitro_enclaves/ne_pci_dev.c

nitro_enclaves: Upstream Linux kernel v5.17 rc1 patches

---

.gitignore
Cargo.lock
Cargo.toml
SPECS/aws-nitro-enclaves-cli.spec
THIRD_PARTY_LICENSES_RUST_CRATES.html
sources

Update Cargo.lock/.toml and RPM spec for 1.2.0 release

nitro-cli: Update Cargo.lock/.toml and RPM spec for 1.2.0 release

---

src/utils.rs

Replace clutered timeout code with a TimerFd added
to epoll.
TimerFd is armed with `disconnect_timeout` seconds
and when the timer fires, the reading loop breakes.

Refactor console disconnect timeout feature

---

src/common/document_errors.rs

Rust 1.62.0 comes with a new clippy warn:
https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string.
It complains about code like:
```
let mut s = String::new();
s += &format!("0x{:X}", 1024);
s.push_str(&format!("0x{:X}", 1024));
```
which does one extra heap allocation than necessary.
Since we promote all warnings to errors, builds on 1.62.0 will fail.
We refactor construct_backtrace() to allocate, format and return the
backtrace string in a single go and add a test to ensure the format
stays consistent.
Signed-off-by: Sabin Rapan <sabrapan@amazon.com>

documents_errors: Fix clippy warn format_push_string

---

enclave_build/src/docker.rs
enclave_build/src/lib.rs
enclave_build/src/yaml_generator.rs
src/common/mod.rs
src/common/signal_handler.rs
src/enclave_proc/cpu_info.rs

Fix a set of clippy warnings in the Nitro CLI codebase.

nitro-cli: Fix clippy warnings

---

src/enclave_proc/connection_listener.rs

In case a signal handler is triggered during
waiting, resume the epoll_wait() again in order
to avoid exiting and terminating the managed
nitro enclave.
Signed-off-by: Alexandru Ciobotaru <alcioa@amazon.com>

cli/enclave_proc: handle EINTR for epoll_wait()

---

Cargo.lock
THIRD_PARTY_LICENSES_RUST_CRATES.html

Crate updates

---

Cargo.lock
Cargo.toml
SPECS/aws-nitro-enclaves-cli.spec
THIRD_PARTY_LICENSES_RUST_CRATES.html
sources

update SPEC for 1.2.2 release

---

bootstrap/allocator.yaml
docs/centos_stream_8_how_to_install_nitro_cli_from_github_sources.md
docs/fedora_34_how_to_install_nitro_cli_from_github_sources.md
docs/rhel_8.4_how_to_install_nitro_cli_from_github_sources.md
docs/ubuntu_20.04_how_to_install_nitro_cli_from_github_sources.md
src/common/document_errors.rs
src/enclave_proc/commands.rs
src/enclave_proc/resource_manager.rs
src/lib.rs

- Add a sentences which hints that more memory might be allocated.
- Fix some typos during this process

Improve help text of the memory argument

---

Cargo.lock
src/common/logger.rs

Update dependencies:
* chrono
* base64
* bindgen
* tokio

Update weekly dependencies

---

Cargo.lock

Update aws-nitro-enclaves-cose and serde dependencies

Update aws-nitro-enclaves-cose and serde dependencies

---

.github/workflows/ci.yml

Fix "Check dependencies for licenses" check

---

Cargo.lock

Downgrade openssl to 0.10.62

---

Cargo.lock

- openssl-sys to 0.9.98
- shlex to 1.2.0

Downgrade openssl-sys and shlex

---

sources

Update the sources file for v1.3.0.

Prepare for Release v1.3.0 (2)

---

sources

Update the sources file for v1.3.0.

Prepare for Release v1.3.0 (3)

---

Cargo.lock
Cargo.toml
SPECS/aws-nitro-enclaves-cli.spec
THIRD_PARTY_LICENSES_RUST_CRATES.html
sources

Update the nitro-cli version to 1.3.2 for a new release.

Prepare 1.3.2 release

---

Cargo.lock
Cargo.toml
SPECS/aws-nitro-enclaves-cli.spec
sources

**Issue #, if available:** -
```
Prepare 1.3.3 release
Update the nitro-cli version to 1.3.3 for a new release.
```
---

Prepare 1.3.3 release

---

Cargo.lock
Cargo.toml
SPECS/aws-nitro-enclaves-cli.spec
THIRD_PARTY_LICENSES_RUST_CRATES.html
sources

**Issue #, if available:**
```
Prepare 1.3.4 release
Update the nitro-cli version to 1.3.4 for a new release.
```

Prepare 1.3.4 release

---

Cargo.lock
Cargo.toml

This commit updates openssl to 0.10.70.

Bump openssl version

---

SPECS/aws-nitro-enclaves-cli.spec
THIRD_PARTY_LICENSES_RUST_CRATES.html
sources

Prepare release 1.4.3, updating various dependencies
Prepares dependency updates for RPM release.

Prepare release 1.4.3

---

Cargo.lock
Cargo.toml

Update Cargo.toml/Cargo.lock to release 1.4.3

Update Cargo files to latest release 1.4.3
